on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: bitsgroupregistry.azurecr.io
        username: ${{ secrets.acr_bitsgroupregistry_username }}
        password: ${{ secrets.acr_bitsgroupregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/runtime" -f  "runtime/Dockerfile" -t bitsgroupregistry.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=runtime/Dockerfile
        docker push bitsgroupregistry.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: bitsgroupregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_bitsgroupregistry_username }}
        container-registry-password: ${{ secrets.acr_bitsgroupregistry_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          bitsgroupregistry.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth
